before_install: npm install npm@latest --global
cache:
  directories:
    - $HOME/.npm
dist: xenial
env:
  global:
    - secure: Zzz+CUQ7k6dLlh1d0VL/M914j58CEvVcvPi2ctOwYA7PiF8qc6DgBNN1hh6jxBey+2y9yGTgqdNR1ks/gydztqs8Wp4VFFPJf6yO8CsDfhuTIhcO0nUiJysmcfOvFbHcevplqdicWCEhiqjswNrCgTt7byC6r1Q/yVlM3AzVNYFrEx9fzJQNZKZHCZPAIB1SnogAlOjyrfUGrj8YzTn2/cCcwd8YyekEioqHNaep6By2etJh2zE5qW9HpwED39WNdEIDXBdyRCMJtXbU37sQTNnl4AmdWu25h4fok4m2ptF4Ri0Jk2pdXhOMLoBdE2rxDWwXODvslBI03Cj91P1inslM1Y9D+ZHvDZakVaDkWN27LARbk50ZPt0FeJjtI8w9GC7IK3lq3uDLOHbfOoh1+09B+MPcKKgJXErSGEFjV5Y5Z0iOGQYF0eii5DC3D4HUmTkJM/ZRzNAF5Evxgmn4SAP3NBCRknlI8XiUOw+qRxNTz15zzEQJn/URmZicjIVJfFPPwdb5zi0n7cTUXUsvqBUM1DkTltJA9EYI3k/9oGzSLW0nobM747vMq4cv/5cNEmAoD89nlj8UKh3fnWyuDhHYYVq4UJhZcxz1DXl/usYRu+vyz5FcjcJC+hXUyrrWZhQ5WP/aT2lnAp4+my/CqFYyIfCyOlnDuiDd2liFHfQ=
    - secure: i1QarWDCEiAdMgYO9EjKE+EUT93H/KppBeiIXNwt55AFe1+j7VYBr69W6daMS/cwBHUIaSe/451y4rV6HVx/67POF5rUE6/WJ+CiCraVD59akbUJjqDlZMEjXkkbctefykRmRvvqLrPBx0GbRAae9beei1S8Xh5gfUSfLDnWY7n/awb/UwLCwE43FhK9oKCAVonbDsTADE4ys7MgY1sm2Br5ulmH5Mn3wqWJ/d30S+rqoNaiVfcIlTjc2YkEC6F6EKhrc/VwQUxTYjSuw4IWCCp191iUk+akyEShpLPH91YqBW2gVaZTLQu/IDJZaFVIyED2LeVIVSY1Pja/0G5UPDlkoZd5U0KHrHRZtWZd5AY4wDxz61xpsD2n+d6VVy7yy0FKH3ZD7PTm3rraS1KSrNdVVdzF1ju+ASs3/D0RfR04GFq1UqF/mW2iiIzeZKmc9Mh220ikdeY+N/WSTkqJ0OZYfmvHrOsKuh1aXNJfRW+XArHgmTfR8jFR4KPFICeuPSziut98h7hahC3YSxaFhFuHcdGV8PQ0/fa49zt5w4ggTOgPW8Vt10Ol6NdvO6SjkERrYbmDaSjY+InAfmbjPDnUM8Yw5vru2+t0QH6keV2OQtfMZFQ+68eAgx3TECXc/SVUvXK6HfzpxtWuY4+6JBn0znhVYIsmgsDYHuKbDIY=
install: npm ci || (rm -rf node_modules && npm install)
language: node_js
node_js:
  - 10
  - 12
