before_install: npm install npm@latest --global
cache:
  directories:
    - $HOME/.npm
dist: xenial
env:
  global:
    - secure: fMRplqHMWPcjhyNgCBzy/zNZ7FHy4FDRhA2NLhRc1v0FMGdTaGYQWBDOn8qhw9hJKk8UUrvPre2OgM+xfVTfSBdpJimkJwZIKbq+9GOtlk4ucrEJa6lTczyOCkuA3cXL+CZMtx4ukdyJISE091/3OjWkbteDp/k8zzc/dpwW1V+mwTUOJB/iN5/J8ruI4fgA69jnuTaGVbSHWFHaiuyG0zetMzDYz5E++nJsKHb37w78nRq5S4JPR2XE7u9xvge3+Xti40mfgngeA6Wl9UwerDUGizDdNp/haZ6jRKYPQesgPXNw/PbiFnsySAwcUaAjnVCtiXkiIcGuJ4NKvTcAK/f1XJhV7/8TMvjAgpvGrTk5yyteZ6HW8T72Ytmj961uzOcDAk4WlSU7zEy84MAh+9aE4ZwhyuFnS5mNJ/zGoy4iQaqE+UbUEndEy65yxHYQGRQvPWT3PbfuSpPbW6syzvNb+jClul6BFPAfvPa6q6EjnKqJ+ixoCrmjC47jqW8iUPBetjjSzmSpUwXmj+4rKY7yiTVnB2zHJcQ43HJeSGTT74Q/fV23nBap2e8a0a+pIU2SZJI0JA+wT1KBT0EpIYLiepVT5br5O6AH1mrZGQeM51dxeL60wBBM65APjBVvz75JMrIVE0okquCmJ0Gl2V9kaVWtquoYOaIwONm8SR8=
    - secure: HhsmUr/LGo2gSK6a/S65HtV3RlN2eN/RQFOBS4/GcBp9UdYPibnrQLp3ApNVOKxUmmow7IhXIARVvbobEWYX4XEohVDrtC3f2bWz9RFAxYK5xSBep+vLyagF0f8mWCDk20ZA5tBA+wMoV8mf21mlKI+HLNxsliArwDKjznH8eiBeZvdqGRHkie05HF7HWjIxKQhImiGoaVGN5B1KEBddln9lLiz5Aevre9L/CkDc3kmlSeJWCKSwwhx5KXfAX5osxYCaZK5VkTFi15lE5CdwahFFwTgqZyFg+Qu3/zwFV1aljq1cMx41JxRgR5Jq54Pf3CVBG3nUIu8C0Jaq9egQ1velYUa027goFZiycnxoHaiIz5EnACGwu13/xFqAsDnpQNz3OWdvqMvQvfKE38wRJQv3bg5TQxE+VAWg/6VRSovc59vb5T/8naskdQ2K7BP25oU94upVfMaNvOi2cXtvMrEHwLga05L93NFII0jLMin2zweplnSunmD8IewxIkrvVR7a+f7XjNAW2bZlCg35haCWsSr27jSIWO7D8CsRxcHdvBK9eHFd4KLOcn9WGBSFv6aVs3cZ3/SKtd0whLMuMLMmg2idAw3DgzBFw7xQeix6J4dRpR+cibMaqkr5+wrtXWSE+ZlkwH+7HxuqIiMW8U9RsYW60Jm0O9kblyqPVTI=
install: npm ci || (rm -rf node_modules && npm install)
language: node_js
node_js:
  - 10
  - 12
